### ISSUE TITLE
gradient selector is blank

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/Customized#11]
![image](https://user-images.githubusercontent.com/79767244/129181003-cf894845-8df2-4662-9be6-8a09619a315b.png)

@CST1229 you're assigned

**Comment by CST1229** [comment]
Weird. I can't reproduce.
![pic](https://user-images.githubusercontent.com/68464103/129181906-d61d3140-19b1-4809-8b35-758e013a97d0.png)
My browser / operating system: Windows NT 10.0, Firefox 92.0, No Flash version detected

**Comment by CodeGuy92** [comment]
This seems weird. It happened to me when i first opened the page. When i reloaded it, it was working fine.

**Comment by CodeGuy92** [comment]
My browser / operating system: Windows NT 10.0, Chrome 92.0.4515.131, No Flash version detected
