### ISSUE TITLE
How to submit your art for display!

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/Customized#15]
Do you want your art (Made with Customized) to show up on the official Customized Website?
Just follow these steps:

1. Add your username with the Style Script font in the corner of your art. [Like this!](https://assets.scratch.mit.edu/get_image/.%2E/601639b7558b2fa81c6cb64c785a21a6.png)
2. Download your art using the "Download" button
3. Share the file (.zip), title of the art & your scratch username here
4. Comment the URL of your github comment in https://scratch.mit.edu/studios/30169057/comments
5. Your art will be added soon, just wait a few hours.

**Comment by CodeGuy92** [comment]
That was a bad idea

**Comment by CST1229** [comment]
> 
> 
> That was a bad idea

Why?
