### ISSUE TITLE
library code isn't efficient

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/Customized#18]
I feel like instead of having to add the costumes in 2 files (lib/index & lib.js) maybe we should delete lib/index and just do a document.replace method, then do a "for" loop for each costume in the array. What do you guys think?

**Comment by CodeGuy92** [comment]
@CST1229 hlep

**Comment by CST1229** [comment]
Maybe. Also as a side note I've got a hex color input working in my mod so expect a PR sometime.

**Comment by CodeGuy92** [comment]
> Maybe.

So do u think i should add this?

> Also as a side note I've got a hex color input working in my mod so expect a PR sometime.

nice

**Comment by CST1229** [comment]
> So do u think i should add this?

Yes, you should. But I'm also doing other things too.
