### ISSUE TITLE
Swatches don't actually switch colors

### ISSUE THREAD

**Issue by CodeGuy92** [CodeGuy92/Customized#2]
Swatches don't actually switch colors. They move the sliders, and make it appear like the color was changed, but in reality, nothing changed.

This needs to get fixed.

**Comment by CodeGuy92** [comment]
![image](https://user-images.githubusercontent.com/79767244/128908420-2c6bc525-7b1e-46ca-ac59-81d79b9fc21e.png)

**Comment by CST1229** [comment]
Also, for reference,  in nono word (idk if i can mention browser extensions here)'s repo, the set color code is at addons/color-picker/paint-editor.js and the redux getter API is at addon-api/content-script/Tab.js.

**Comment by CodeGuy92** [comment]
> Also, for reference, in nono word (idk if i can mention browser extensions here)'s repo, the set color code is at addons/color-picker/paint-editor.js and the redux getter is at addon-api/content-script/Tab.js, which [the redux API] is a single line of code excluding imports: `this.redux = new ReduxHandler();`

I'm getting too complicated here.
Maybe i can just...
```
let element = document.getElementsByClassName("slider_container_2U0n6")[0];
element.click();
```

**Comment by CodeGuy92** [comment]
wait
https://stackoverflow.com/questions/61376278/simulate-a-3-pixel-drag-on-draggable-elem

**Comment by CodeGuy92** [comment]
So i made a small script to trigger the eyedropper. Dude, so much easier!
```
let element = document.getElementsByClassName("slider_handle_2M_mA")[0];

const mouseDownEvent = new MouseEvent('mousedown', {
  clientX: element.getBoundingClientRect().left,
  clientY: element.getBoundingClientRect().top,
  bubbles: true,
  cancelable: true
});

const mouseMoveEvent = new MouseEvent('mousemove', {
  clientX: element.getBoundingClientRect().left,
  clientY: element.getBoundingClientRect().top,
  bubbles: true,
  cancelable: true
});

const mouseUpEvent = new MouseEvent('mouseup', {
  bubbles: true,
  cancelable: true
});

element.dispatchEvent(mouseDownEvent);

element.dispatchEvent(mouseMoveEvent);

element.dispatchEvent(mouseUpEvent);
```

**Comment by CodeGuy92** [comment]
I'll just wrap that in a small function, trigger it in every selection, and we're done.

**Comment by CST1229** [comment]
Doesn't seem to work for me. It doesn't trigger the eyedropper nor drag any slider.

**Comment by CodeGuy92** [comment]
> That doesn't seem to work for me. It doesn't trigger the eyedropper nor drag any slider.
> EDIT: Also I'm on Firefox.

Yeah i fixed some stuff. I just pushed a commit to the repo. Wait for Git Pages to build (or download the repo to get a little fancy) and tell me if there are any compatibillity issues.

**Comment by CST1229** [comment]
It seems to work for me!
![rpP8fRXvJh](https://user-images.githubusercontent.com/68464103/128913993-56bcda66-6b46-4cc3-861f-cfafe909ca8a.gif)

**Comment by CodeGuy92** [comment]
> It seems to work for me!
> ![rpP8fRXvJh](https://user-images.githubusercontent.com/68464103/128913993-56bcda66-6b46-4cc3-861f-cfafe909ca8a.gif)

Niiiiceee! Since it works, ima close the issue as resolved.
