### ISSUE TITLE
URL no longer works

### ISSUE THREAD

**Issue by Dhuls-Scratch** [CodeGuy92/Customized#21]
See [this comment](https://scratch.mit.edu/users/LankyBox01/#comments-154929709). Basically, all subdomains of leahcimto.com made for other users were deleted. This means that Customized no longer works. All attempts to access it result in a DNS_PROBE_FINISHED_NXDOMAIN error. I think you should use CodeGuy92.github.io/Customized (the former redirect), as there are no issues with registration and such.

**Comment by CodeGuy92** [comment]
Welp, time to get a new domain.

**Comment by CodeGuy92** [comment]
http://www.thatrandomguy.tk/
